use newer p7zip which is not in xenial repos

diff --git a/src/dl_npp b/src/dl_npp
--- a/src/dl_npp
+++ b/src/dl_npp
@@ -12,7 +12,6 @@
 dlnpp () {
     ver=$(wget https://notepad-plus-plus.org/download -q -S -O - 2>&1 | grep 'Version</t' | cut -c19-24 | sed 's| -||' | sed 's/ //g')
     repover=$(echo $ver | cut -c01-1)
-    ARCHITECTURE=$(dpkg --print-architecture)
     if [ "${ARCHITECTURE}" = "amd64" ]; then
      wget https://notepad-plus-plus.org/repository/$repover.x/$ver/npp.$ver.Installer.x64.exe &> /dev/null
      7z x -aos "npp.$ver.Installer.x64.exe" -x'!change.log' -x'!doLocalConf.xml' -x'!LICENSE' -x'!NppShell_06.dll' -x'!readme.txt' -o"usr/share/notepad-plus-plus"
@@ -23,6 +22,31 @@ dlnpp () {
      echo "ERROR! notepad-plus-plus only produces software for amd64 and i386. Failing the build here."
      exit 1
     fi
+}
+
+dli7z16 () {
+    ARCHITECTURE=$(dpkg --print-architecture)
+    if [ "${ARCHITECTURE}" = "amd64" ]; then
+    debs="https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip_16.02+dfsg-4_amd64.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip-full_16.02+dfsg-4_amd64.deb"
+    debsi="p7zip_16.02+dfsg-4_amd64.deb p7zip-full_16.02+dfsg-4_amd64.deb"
+    elif [ "${ARCHITECTURE}" = "i386" ]; then
+    debs="https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091329/+files/p7zip_16.02+dfsg-4_i386.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091329/+files/p7zip-full_16.02+dfsg-4_i386.deb"
+    debsi="p7zip_16.02+dfsg-4_i386.deb p7zip-full_16.02+dfsg-4_i386.deb"
+    else
+     echo "ERROR! No amd64 or i386 system found. Failing the build here."
+     exit 1
+    fi
+
+    for dldebs in $debs
+    do
+    wget $dldebs &> /dev/null
+    done
+
+    for pkgdebins in $debsi
+    do
+    sudo apt install ./$pkgdebins -y &> /dev/null
+    rm $pkgdebins
+    done
 }
 
 mknpp () {
@@ -56,6 +80,7 @@ EOF1
 sed -i -e 's|Version=|Version='"$ver"'|g' notepad-plus-plus.desktop
 }
 
+dli7z16
 dlnpp
 mknpp
 mkdsk
